### PR TITLE
Added TranslationGuide

### PR DESCRIPTION
**Pull request by dsgpaiva**
WIP. There's a stupid bug where text just doesn't render right.

### CODE REVIEW

**Comment by pedrofracassi** [comment]
> stupid bug where text just doesn't render right

aka "I was too lazy to add proper CSS to this shit"

**Comment by dsgpaiva** [comment]
@pedrofracassi nah, new lines aren't working properly aswell

**Comment by dsgpaiva** [comment]
#, ## and ### aren't working aswell, etc.

**Comment by pedrofracassi** [comment]
Might wanna add some [props](https://github.com/miaolz123/vue-markdown#props) to make it render correctly.

**Comment by dsgpaiva** [comment]
HEY FLASH NEWS
THEY'RE ALREADY ACTIVATED BY DEFAULT

**Pull request closed without merging**
